apiVersion: v1
kind: Pod
metadata:
  name: pod-sc-local
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      volumeMounts:
        - mountPath: /volume-container
          name: primeiro-pv
  volumes:
    - name: primeiro-pv
      persistentVolumeClaim: 
        claimName: pvc-2
        